### ISSUE TITLE
Error with Austrian holidays from version 0.22

### ISSUE THREAD

**Issue by georgpfolz** [vacanza/python-holidays#1404]
```
import holidays
at_holidays = holidays.AT(state=9)
'2023-12-25' in at_holidays
```

This code works fine up to version 0.21.13, but breaks at version 0.22 and above:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/holidays/holiday_base.py", line 406, in __contains__
    cast("Mapping[Any, Any]", self), self.__keytransform__(key)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/holidays/holiday_base.py", line 384, in __keytransform__
    self._populate(dt.year)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/holidays/countries/austria.py", line 34, in _populate
    super()._populate(year)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/holidays/holiday_base.py", line 794, in _populate
    self._add_subdiv_holidays()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/holidays/holiday_base.py", line 764, in _add_subdiv_holidays
    self, f"_add_subdiv_{self.subdiv.lower()}_holidays", None
AttributeError: 'int' object has no attribute 'lower'
```

It's the same in Python 3.9. I got the error on MacOS Catalina as well as FreeBSD 13.2

**Comment by hinson-x** [comment]
I got somewhat a similar error. 
AttributeError: module 'holidays' has no attribute 'CountryHoliday'

The same code was working just a couple of days ago on OSX. Now I have the same exact line on another OS (Debian), same error.

**Comment by arkid15r** [comment]
Hi @georgpfolz,
thanks for the report!

The `state` arg has been deprecated for a while. You can use either `at_holidays = holidays.AT(subdiv=9)` or `at_holidays = holidays.AT(state="9")` to avoid the error. 

I'll look into what can be done to improve the subdivision handling on our side.

Thank you!

**Comment by hinson-x** [comment]
Hello @arkid15r 
Actually I found the issue. I was not too smart where I named my new test python file holiday.py too, so it was trying to.... import itself thus not finding any functions/attributes. Thanks anyhow, appreciate it.
